#!/usr/bin/env python3
import sys
import json
import os

sys.path.append(os.path.join(os.path.dirname(__file__), ".."))
from streaming_stats.streaming_stats import stats


def stdin_to_iterable():
    for line in sys.stdin:
        yield float(line)


def main():
    s = stats(stdin_to_iterable())
    print(json.dumps(s))


if __name__ == "__main__":
    main()
